- name: variables in ansible
  hosts: mongodb
  vars:
    name: anand
    age: 26
    city: Hyderabad
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: "Hello I'm learning ansible"
    - name: printing from play level variables
      ansible.builtin.debug:
        msg: "Hello, I'm {{name}}({{age}}) from {{city}}"