- name: variables from files
  hosts: localhost #managing the ansible server itself
  vars_files:
  - variables.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "Hello, I'm {{Name}}({{Age}}) from {{City}}"