- name: variables from prompt
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: enter user name
      private: false
    - name: PASSWORD
      prompt: enter password
      private: true
  tasks:
  - name: print variable values
    ansible.builtin.debug:
      msg: "username: {{USERNAME}} and password: {{PASSWORD}}"