- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: anand - play
  tasks:
  - name: variable at task level
    ansible.builtin.debug:
      msg: "Name from command line: {{NAME}}"

# command line
# task
# file
# prompt