- name: testing variable precedence
  hosts: mongodb
  tasks:
  - name: variable at task level
    ansible.builtin.debug:
      msg: "Name from command line: {{NAME}}"

#1 command line
#2 task
#3 file
#4 prompt
#5 play
#6 inventory
#7 Roles