- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: anand - play
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: enter your name
    private: false
  tasks:
  - name: variable at task level
    vars:
      NAME: anand - task
    ansible.builtin.debug:
      msg: "Name from command line: {{NAME}}"