- name: install packages through loops
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - nginx
    - postfix