- name: install packages through loops
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'nginx',state: 'installed'}
    - {name: 'postfix',state: 'absent'}